.global inc_vs_size
.set inc_vs_size, 0f-inc_vs
.global inc_vs
inc_vs:
	.incbin "vs.bin"
0:

.align 4

.global inc_ps_fb_size
.set inc_ps_fb_size, 0f-inc_ps_fb
.global inc_ps_fb
inc_ps_fb:
	.incbin "ps_fb.bin"
0:

.align 4

.global inc_ps_combiner_1c1a_size
.set inc_ps_combiner_1c1a_size, 0f-inc_ps_combiner_1c1a
.global inc_ps_combiner_1c1a
inc_ps_combiner_1c1a:
	.incbin "ps_combiner_1c1a.bin"
0:

.align 4

.global inc_ps_combiner_1c2a_size
.set inc_ps_combiner_1c2a_size, 0f-inc_ps_combiner_1c2a
.global inc_ps_combiner_1c2a
inc_ps_combiner_1c2a:
	.incbin "ps_combiner_1c2a.bin"
0:

.align 4

.global inc_ps_combiner_1c3a_size
.set inc_ps_combiner_1c3a_size, 0f-inc_ps_combiner_1c3a
.global inc_ps_combiner_1c3a
inc_ps_combiner_1c3a:
	.incbin "ps_combiner_1c3a.bin"
0:

.align 4

.global inc_ps_combiner_1c4a_size
.set inc_ps_combiner_1c4a_size, 0f-inc_ps_combiner_1c4a
.global inc_ps_combiner_1c4a
inc_ps_combiner_1c4a:
	.incbin "ps_combiner_1c4a.bin"
0:

.align 4

.global inc_ps_combiner_2c1a_size
.set inc_ps_combiner_2c1a_size, 0f-inc_ps_combiner_2c1a
.global inc_ps_combiner_2c1a
inc_ps_combiner_2c1a:
	.incbin "ps_combiner_2c1a.bin"
0:

.align 4

.global inc_ps_combiner_2c2a_size
.set inc_ps_combiner_2c2a_size, 0f-inc_ps_combiner_2c2a
.global inc_ps_combiner_2c2a
inc_ps_combiner_2c2a:
	.incbin "ps_combiner_2c2a.bin"
0:

.align 4

.global inc_ps_combiner_2c3a_size
.set inc_ps_combiner_2c3a_size, 0f-inc_ps_combiner_2c3a
.global inc_ps_combiner_2c3a
inc_ps_combiner_2c3a:
	.incbin "ps_combiner_2c3a.bin"
0:

.align 4

.global inc_ps_combiner_2c4a_size
.set inc_ps_combiner_2c4a_size, 0f-inc_ps_combiner_2c4a
.global inc_ps_combiner_2c4a
inc_ps_combiner_2c4a:
	.incbin "ps_combiner_2c4a.bin"
0:

.align 4

.global inc_ps_combiner_3c1a_size
.set inc_ps_combiner_3c1a_size, 0f-inc_ps_combiner_3c1a
.global inc_ps_combiner_3c1a
inc_ps_combiner_3c1a:
	.incbin "ps_combiner_3c1a.bin"
0:

.align 4

.global inc_ps_combiner_3c2a_size
.set inc_ps_combiner_3c2a_size, 0f-inc_ps_combiner_3c2a
.global inc_ps_combiner_3c2a
inc_ps_combiner_3c2a:
	.incbin "ps_combiner_3c2a.bin"
0:

.align 4

.global inc_ps_combiner_3c3a_size
.set inc_ps_combiner_3c3a_size, 0f-inc_ps_combiner_3c3a
.global inc_ps_combiner_3c3a
inc_ps_combiner_3c3a:
	.incbin "ps_combiner_3c3a.bin"
0:

.align 4

.global inc_ps_combiner_3c4a_size
.set inc_ps_combiner_3c4a_size, 0f-inc_ps_combiner_3c4a
.global inc_ps_combiner_3c4a
inc_ps_combiner_3c4a:
	.incbin "ps_combiner_3c4a.bin"
0:

.align 4

.global inc_ps_combiner_4c1a_size
.set inc_ps_combiner_4c1a_size, 0f-inc_ps_combiner_4c1a
.global inc_ps_combiner_4c1a
inc_ps_combiner_4c1a:
	.incbin "ps_combiner_4c1a.bin"
0:

.align 4

.global inc_ps_combiner_4c2a_size
.set inc_ps_combiner_4c2a_size, 0f-inc_ps_combiner_4c2a
.global inc_ps_combiner_4c2a
inc_ps_combiner_4c2a:
	.incbin "ps_combiner_4c2a.bin"
0:

.align 4

.global inc_ps_combiner_4c3a_size
.set inc_ps_combiner_4c3a_size, 0f-inc_ps_combiner_4c3a
.global inc_ps_combiner_4c3a
inc_ps_combiner_4c3a:
	.incbin "ps_combiner_4c3a.bin"
0:

.align 4

.global inc_ps_combiner_4c4a_size
.set inc_ps_combiner_4c4a_size, 0f-inc_ps_combiner_4c4a
.global inc_ps_combiner_4c4a
inc_ps_combiner_4c4a:
	.incbin "ps_combiner_4c4a.bin"
0:

.align 4

.global inc_ps_combiner_slow_size
.set inc_ps_combiner_slow_size, 0f-inc_ps_combiner_slow
.global inc_ps_combiner_slow
inc_ps_combiner_slow:
	.incbin "ps_combiner_slow.bin"
0: